name: cevicheria_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.4
  google_fonts: ^6.1.0
  glassmorphism_ui: 0.3.0
  intl: ^0.18.1
  iconly: ^1.0.1
  flutter_local_notifications: ^17.1.2
  audioplayers: ^5.2.1
  device_info_plus: ^11.4.0
  just_audio: ^0.10.2
  shared_preferences: ^2.5.3
  firebase_messaging: ^14.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/camaron.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/notificacion.mp3
