name: cevicheria_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  google_fonts: ^6.2.1
  glassmorphism_ui: 0.3.0
  intl: ^0.20.2
  icons_plus: ^5.0.0
  material_symbols_icons: ^4.2506.0
  iconly: ^1.0.1
  flutter_local_notifications: ^19.2.1
  audioplayers: 6.4.0
  shared_preferences: ^2.5.3
  firebase_messaging: ^15.2.6

  uuid: any
  collection: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/camaron.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/icon/camaron.ico
    - assets/notificacion.mp3
