// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4InQ9jt3dttVark87f1_ExYFTp7Ik5Sw',
    appId: '1:116307650186:web:bb1fe597b5f7cada7aaf73',
    messagingSenderId: '116307650186',
    projectId: 'cevicheria-app-8c9d8',
    authDomain: 'cevicheria-app-8c9d8.firebaseapp.com',
    storageBucket: 'cevicheria-app-8c9d8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEPa6-cAQEtsSL2-52Az0TmM32M27LvbY',
    appId: '1:116307650186:android:838dbc41795593137aaf73',
    messagingSenderId: '116307650186',
    projectId: 'cevicheria-app-8c9d8',
    storageBucket: 'cevicheria-app-8c9d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeFDpzm_Tw101GiKCiNcL_Ql7JiFtwZVM',
    appId: '1:116307650186:ios:87f0235529c2578f7aaf73',
    messagingSenderId: '116307650186',
    projectId: 'cevicheria-app-8c9d8',
    storageBucket: 'cevicheria-app-8c9d8.firebasestorage.app',
    iosBundleId: 'com.example.cevicheriaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeFDpzm_Tw101GiKCiNcL_Ql7JiFtwZVM',
    appId: '1:116307650186:ios:87f0235529c2578f7aaf73',
    messagingSenderId: '116307650186',
    projectId: 'cevicheria-app-8c9d8',
    storageBucket: 'cevicheria-app-8c9d8.firebasestorage.app',
    iosBundleId: 'com.example.cevicheriaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4InQ9jt3dttVark87f1_ExYFTp7Ik5Sw',
    appId: '1:116307650186:web:6b321774e0e1830f7aaf73',
    messagingSenderId: '116307650186',
    projectId: 'cevicheria-app-8c9d8',
    authDomain: 'cevicheria-app-8c9d8.firebaseapp.com',
    storageBucket: 'cevicheria-app-8c9d8.firebasestorage.app',
  );
}
